# Generated by Django 5.2.8 on 2025-11-09 11:59

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('seeing_flag', models.BooleanField(blank=True, null=True)),
                ('hearing_flag', models.BooleanField(blank=True, null=True)),
                ('mobility_flag', models.BooleanField(blank=True, null=True)),
                ('fine_motor_flag', models.BooleanField(blank=True, null=True)),
                ('speech_flag', models.BooleanField(blank=True, null=True)),
                ('learning_flag', models.BooleanField(blank=True, null=True)),
                ('memory_flag', models.BooleanField(blank=True, null=True)),
                ('attention_flag', models.BooleanField(blank=True, null=True)),
                ('behaviour_flag', models.BooleanField(blank=True, null=True)),
                ('social_flag', models.BooleanField(blank=True, null=True)),
                ('anxiety_freq', models.IntegerField(blank=True, null=True)),
                ('depression_freq', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrolments', to='integrations.emisclasslevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolments_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='integrations.emisschool')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrolments', to='integrations.emiswarehouseyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='inclusive_ed.student')),
            ],
            options={
                'ordering': ['school_year__code', 'school__emis_school_no', 'student_id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='student_enrolments', through='inclusive_ed.StudentSchoolEnrolment', to='integrations.emisschool'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=models.Index(fields=['school', 'school_year'], name='inclusive_e_school__356f12_idx'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=models.Index(fields=['student', 'school_year'], name='inclusive_e_student_2554af_idx'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=models.Index(fields=['class_level'], name='inclusive_e_class_l_dab5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['answers'], name='inclusive_e_answers_dd6152_gin'),
        ),
        migrations.AddConstraint(
            model_name='studentschoolenrolment',
            constraint=models.UniqueConstraint(fields=('student', 'school', 'school_year'), name='uq_student_school_year'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='inclusive_e_last_na_f76088_idx'),
        ),
    ]
