# Generated by Django 5.2.8 on 2025-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_ed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_inclusive_ed', 'Can access the Disability-Inclusive Education app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
