# Generated by Django 5.2.8 on 2025-11-12 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_ed', '0002_permissionsanchor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='studentschoolenrolment',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolments_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
