# Generated by Django 5.2.8 on 2025-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_ed', '0003_rename_updated_at_student_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsanchor',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_inclusive_ed', 'Can access the Disability-Inclusive Education app'),), 'verbose_name': 'Disability-Inclusive Education app', 'verbose_name_plural': 'Disability-Inclusive Education app'},
        ),
        migrations.RemoveIndex(
            model_name='studentschoolenrolment',
            name='inclusive_e_answers_dd6152_gin',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='anxiety_freq',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='attention_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='behaviour_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='depression_freq',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='fine_motor_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='hearing_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='learning_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='memory_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='mobility_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='seeing_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='social_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='speech_flag',
        ),
        migrations.RemoveField(
            model_name='studentschoolenrolment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft10_difficulty_walking_compare_to_others',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft11_difficulty_picking_up_small_objects',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft12_difficulty_being_understood',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft13_difficulty_learning',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft14_difficulty_remembering',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft15_difficulty_concentrating',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft16_difficulty_accepting_change',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft17_difficulty_controlling_behaviour',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft18_difficulty_making_friends',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft19_anxious_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'A few times a year'), (5, 'Never')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft1_wears_glasses',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft20_depressed_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'A few times a year'), (5, 'Never')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft2_difficulty_seeing_with_glasses',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft3_difficulty_seeing',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft4_has_hearing_aids',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft5_difficulty_hearing_with_aids',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft6_difficulty_hearing',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft7_uses_walking_equipment',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft8_difficulty_walking_without_equipment',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='cft9_difficulty_walking_with_equipment',
            field=models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True),
        ),
    ]
