# Generated by Django 5.2.8 on 2025-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_ed', '0004_alter_permissionsanchor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentschoolenrolment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
