# Generated by Django 5.2.8 on 2025-12-11 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Disability-Inclusive Education app',
                'verbose_name_plural': 'Disability-Inclusive Education app',
                'permissions': (('access_app', 'Can access the Disability-Inclusive Education app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff')], default='non_teaching', help_text='Type of staff member - teaching or non-teaching', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user account for this staff member', on_delete=django.db.models.deletion.CASCADE, related_name='school_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Staff',
                'verbose_name_plural': 'School Staff',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, help_text='When this assignment began', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When this assignment ended (null = currently active)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(help_text='Job title/role at this school', on_delete=django.db.models.deletion.PROTECT, related_name='job_title_assignments', to='integrations.emisjobtitle')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School where staff is assigned', on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='integrations.emisschool')),
                ('school_staff', models.ForeignKey(help_text='Staff member being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.schoolstaff')),
            ],
            options={
                'verbose_name': 'School Staff Assignment',
                'verbose_name_plural': 'School Staff Assignments',
                'ordering': ['school_staff_id', 'school_id', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='school_staff_members', through='core.SchoolStaffAssignment', to='integrations.emisschool'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cft1_wears_glasses', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True)),
                ('cft2_difficulty_seeing_with_glasses', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft3_difficulty_seeing', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft4_has_hearing_aids', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True)),
                ('cft5_difficulty_hearing_with_aids', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft6_difficulty_hearing', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft7_uses_walking_equipment', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True)),
                ('cft8_difficulty_walking_without_equipment', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft9_difficulty_walking_with_equipment', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft10_difficulty_walking_compare_to_others', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft11_difficulty_picking_up_small_objects', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft12_difficulty_being_understood', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft13_difficulty_learning', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft14_difficulty_remembering', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft15_difficulty_concentrating', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft16_difficulty_accepting_change', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft17_difficulty_controlling_behaviour', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft18_difficulty_making_friends', models.IntegerField(blank=True, choices=[(1, 'No difficulty'), (2, 'Some difficulty'), (3, 'A lot of difficulty'), (4, 'Cannot do at all')], null=True)),
                ('cft19_anxious_frequency', models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'A few times a year'), (5, 'Never')], null=True)),
                ('cft20_depressed_frequency', models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'A few times a year'), (5, 'Never')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrolments', to='integrations.emisclasslevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolments_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolments_updated', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='integrations.emisschool')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrolments', to='integrations.emiswarehouseyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='core.student')),
            ],
            options={
                'ordering': ['school_year__code', 'school__emis_school_no', 'student_id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='student_enrolments', through='core.StudentSchoolEnrolment', to='integrations.emisschool'),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(blank=True, help_text='Organization or department (e.g., Ministry of Education, District Office)', max_length=255)),
                ('position_title', models.CharField(blank=True, help_text='Job title or position within the organization', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user account for this system user', on_delete=django.db.models.deletion.CASCADE, related_name='system_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolstaffassignment',
            index=models.Index(fields=['start_date', 'end_date'], name='core_school_start_d_a01bc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolstaffassignment',
            constraint=models.UniqueConstraint(fields=('school_staff', 'school', 'start_date', 'end_date'), name='uq_school_staff_assignment'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=models.Index(fields=['school', 'school_year'], name='core_studen_school__b8a766_idx'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=models.Index(fields=['student', 'school_year'], name='core_studen_student_b7bed5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentschoolenrolment',
            index=models.Index(fields=['class_level'], name='core_studen_class_l_cf06ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentschoolenrolment',
            constraint=models.UniqueConstraint(fields=('student', 'school', 'school_year'), name='uq_student_school_year'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='core_studen_last_na_d07597_idx'),
        ),
    ]
