# Generated by Django 5.2.8 on 2025-11-07 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_school_no', models.CharField(max_length=32)),
                ('emis_school_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacherassignment_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'emis_school_no'],
                'indexes': [models.Index(fields=['emis_school_no'], name='accounts_te_emis_sc_dca145_idx'), models.Index(fields=['is_active'], name='accounts_te_is_acti_c66937_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'emis_school_no'), name='uq_teacher_school_once')],
            },
        ),
    ]
