# Generated by Django 5.2.8 on 2025-11-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Administrator', 'Administrator')], max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffschoolmembership_created', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to='integrations.emisjobtitle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='integrations.emisschool')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.staff')),
            ],
            options={
                'ordering': ['staff_id', 'school_id', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='staff_members', through='accounts.StaffSchoolMembership', to='integrations.emisschool'),
        ),
        migrations.AddIndex(
            model_name='staffschoolmembership',
            index=models.Index(fields=['login_role'], name='accounts_st_login_r_70b7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffschoolmembership',
            index=models.Index(fields=['start_date', 'end_date'], name='accounts_st_start_d_6daad3_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffschoolmembership',
            constraint=models.UniqueConstraint(fields=('staff', 'school', 'start_date', 'end_date', 'login_role'), name='uq_membership_exact_tuple'),
        ),
    ]
