# Generated by Django 5.2.8 on 2025-12-07 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_last_updated_at_staff_last_updated_by_and_more'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffschoolmembership',
            name='uq_membership_exact_tuple',
        ),
        migrations.RemoveIndex(
            model_name='staffschoolmembership',
            name='accounts_st_login_r_70b7c7_idx',
        ),
        migrations.RemoveField(
            model_name='staffschoolmembership',
            name='login_role',
        ),
        migrations.AddConstraint(
            model_name='staffschoolmembership',
            constraint=models.UniqueConstraint(fields=('staff', 'school', 'start_date', 'end_date'), name='uq_membership_exact_tuple'),
        ),
    ]
